/**
 * @fileoverview
 *
 * This package contains an array of timezones based on conventional options found online.
 * It does not follow any complete data set, but all names are according to the tz format:
 * https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
 *
 * More specifically, the fields in the array are:
 * – offset, a string from '-11:00' to '+14:00' representing the UTC offset
 * - text, a readable text that contains the offset and a longer, descriptive name of the timezone
 * - id, the value from the tz standard
 *
 * Install:
 *  `npm install compact-timezone-list --save`
 *   # or
 *  `yarn add compact-timezone-list`
 *
 *
 *  Example:
 *  const { defaultTimezoneSet } = require('compact-timezone-list');
 *  // or
 *  const { minimalTimezoneSet } = require('compact-timezone-list');
 *
 *  Details:
 *  - The 'defaultTimezoneSet' export provides a long list of options, with multiple
 *  – The `minimalTimezoneSet` export provides one option per offset type, with
 *  a favourite chosen to represent each offset. This is mostly targeted to small,
 *  western-focused apps. But, every UTC offset is included.
 */

/**
 *
 * @type {Array.<{ offset: string, text: string, id: string }>}
 */
module.exports.defaultTimezoneSet = [
    {
        id: -1, text: 'Choose your timezone', disabled: true,
        id: 0, text: 'Africa',
        children: [
            { offset: '+00:00', text: '(GMT+00:00) Africa/Abidjan', id: 'Africa/Abidjan', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Accra', id: 'Africa/Accra', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Addis_Ababa', id: 'Africa/Addis_Ababa', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Algiers', id: 'Africa/Algiers', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Asmara', id: 'Africa/Asmara', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Bamako', id: 'Africa/Bamako', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Bangui', id: 'Africa/Bangui', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Banjul', id: 'Africa/Banjul', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Bissau', id: 'Africa/Bissau', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Blantyre', id: 'Africa/Blantyre', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Brazzaville', id: 'Africa/Brazzaville', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Bujumbura', id: 'Africa/Bujumbura', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Cairo', id: 'Africa/Cairo', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Casablanca', id: 'Africa/Casablanca', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Ceuta', id: 'Africa/Ceuta', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Conakry', id: 'Africa/Conakry', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Dakar', id: 'Africa/Dakar', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Dar_es_Salaam', id: 'Africa/Dar_es_Salaam', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Djibouti', id: 'Africa/Djibouti', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Douala', id: 'Africa/Douala', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/El_Aaiun', id: 'Africa/El_Aaiun', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Freetown', id: 'Africa/Freetown', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Gaborone', id: 'Africa/Gaborone', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Harare', id: '	Africa/Harare', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Johannesburg', id: 'Africa/Johannesburg', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Juba', id: 'Africa/Juba', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Kampala', id: 'Africa/Kampala', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Khartoum', id: 'Africa/Khartoum', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Kigali', id: 'Africa/Kigali', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Kinshasa', id: 'Africa/Kinshasa', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Lagos', id: 'Africa/Lagos', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Libreville', id: 'Africa/Libreville', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Lome', id: 'Africa/Lome', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Luanda', id: 'Africa/Luanda', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Lubumbashi', id: 'Africa/Lubumbashi', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Lusaka', id: 'Africa/Lusaka', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Malabo	', id: 'Africa/Malabo	', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Maputo', id: 'Africa/Maputo', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Maseru', id: 'Africa/Maseru', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Mbabane', id: 'Africa/Mbabane', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Mogadishu', id: 'Africa/Mogadishu', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Monrovia', id: 'Africa/Monrovia', category: 'Africa' },
            { offset: '+03:00', text: '(GMT+03:00) Africa/Nairobi', id: 'Africa/Nairobi', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Ndjamena', id: 'Africa/Ndjamena', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Niamey', id: 'Africa/Niamey', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Nouakchott', id: 'Africa/Nouakchott', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Ouagadougou', id: 'Africa/Ouagadougou', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Porto-Novo', id: 'Africa/Porto-Novo', category: 'Africa' },
            { offset: '+00:00', text: '(GMT+00:00) Africa/Sao_Tome', id: 'Africa/Sao_Tome', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Tripoli', id: 'Africa/Tripoli', category: 'Africa' },
            { offset: '+01:00', text: '(GMT+01:00) Africa/Tunis', id: 'Africa/Tunis', category: 'Africa' },
            { offset: '+02:00', text: '(GMT+02:00) Africa/Windhoek', id: 'Africa/Windhoek', category: 'Africa' },
        ]
  },
    {
        id: 1, text: 'America',
        children: [
            { offset: '−10:00', text: '(GMT−10:00) America/Adak', id: 'America/Adak', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Anchorage', id: 'America/Anchorage', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Anguilla', id: 'America/Anguilla', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Antigua', id: 'America/Antigua', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Araguaina', id: 'America/Araguaina', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Buenos_Aires', id: 'America/Argentina/Buenos_Aires', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Catamarca', id: 'America/Argentina/Catamarca', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Cordoba', id: 'America/Argentina/Cordoba', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Jujuy', id: 'America/Argentina/Jujuy', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/La_Rioja', id: 'America/Argentina/La_Rioja', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Mendoza', id: 'America/Argentina/Mendoza', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Rio_Gallegos', id: 'America/Argentina/Rio_Gallegos', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Salta', id: 'America/Argentina/Salta', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/San_Juan', id: 'America/Argentina/San_Juan', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/San_Luis', id: 'America/Argentina/San_Luis', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Tucuman', id: 'America/Argentina/Tucuman', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Argentina/Ushuaia', id: 'America/Argentina/Ushuaia', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Aruba', id: 'America/Aruba', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Asuncion', id: 'America/Asuncion', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Atikokan', id: 'America/Atikokan', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Bahia', id: 'America/Bahia', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Bahia_Banderas', id: 'America/Bahia_Banderas', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Barbados', id: 'America/Barbados', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Belem', id: 'America/Belem', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Belize', id: 'America/Belize', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Blanc-Sablon', id: 'America/Blanc-Sablon', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Boa_Vista', id: 'America/Boa_Vista', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Bogota', id: 'America/Bogota', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Boise', id: 'America/Boise', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Cambridge_Bay', id: 'America/Cambridge_Bay', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Campo_Grande', id: 'America/Campo_Grande', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Cancun', id: 'America/Cancun', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Caracas', id: 'America/Caracas', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Cayenne', id: 'America/Cayenne', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Cayman', id: 'America/Cayman', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Chicago', id: 'America/Chicago', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Chihuahua', id: 'America/Chihuahua', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Costa_Rica', id: 'America/Costa_Rica', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Creston', id: 'America/Creston', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Cuiaba', id: 'America/Cuiaba', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Curacao', id: 'America/Curacao', category: 'America' },
            { offset: '+00:00', text: '(GMT+00:00) America/Danmarkshavn', id: 'America/Danmarkshavn', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Dawson', id: 'America/Dawson', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Dawson_Creek', id: 'America/Dawson_Creek', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Denver', id: 'America/Denver', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Detroit', id: 'America/Detroit', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Dominica', id: 'America/Dominica', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Edmonton', id: 'America/Edmonton', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Eirunepe', id: 'America/Eirunepe', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/El_Salvador', id: 'America/El_Salvador', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Fort_Nelson', id: 'America/Fort_Nelson', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Fortaleza', id: 'America/Fortaleza', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Glace_Bay', id: 'America/Glace_Bay', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Goose_Bay', id: 'America/Goose_Bay', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Grand_Turk', id: 'America/Grand_Turk', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Grenada', id: 'America/Grenada', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Guadeloupe', id: 'America/Guadeloupe', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Guatemala', id: 'America/Guatemala', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Guayaquil', id: 'America/Guayaquil', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Guyana', id: 'America/Guyana', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Halifax', id: 'America/Halifax', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Havana', id: 'America/Havana', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Hermosillo', id: 'America/Hermosillo', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Indianapolis', id: 'America/Indiana/Indianapolis', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Indiana/Knox', id: 'America/Indiana/Knox', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Marengo', id: 'America/Indiana/Marengo', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Petersburg', id: 'America/Indiana/Petersburg', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Indiana/Tell_City', id: 'America/Indiana/Tell_City', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Vevay', id: 'America/Indiana/Vevay', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Vincennes', id: 'America/Indiana/Vincennes', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Indiana/Winamac', id: 'America/Indiana/Winamac', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Inuvik', id: 'America/Inuvik', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Iqaluit', id: 'America/Iqaluit', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Jamaica', id: 'America/Jamaica', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Juneau', id: 'America/Juneau', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Kentucky/Louisville', id: 'America/Kentucky/Louisville', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Kentucky/Monticello', id: 'America/Kentucky/Monticello', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Kralendijk', id: 'America/Kralendijk', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/La_Paz', id: 'America/La_Paz', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Lima', id: 'America/Lima', category: 'America' },
            { offset: '−08:00', text: '(GMT−08:00) America/Los_Angeles', id: 'America/Los_Angeles', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Lower_Princes', id: 'America/Lower_Princes', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Maceio', id: 'America/Maceio', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Managua', id: 'America/Managua', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Manaus', id: 'America/Manaus', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Marigot', id: 'America/Marigot', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Martinique', id: 'America/Martinique', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Matamoros', id: 'America/Matamoros', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Mazatlan', id: 'America/Mazatlan', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Menominee', id: 'America/Menominee', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Merida', id: 'America/Merida', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Metlakatla', id: 'America/Metlakatla', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Mexico_City', id: 'America/Mexico_City', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Miquelon', id: 'America/Miquelon', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Moncton', id: 'America/Moncton', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Monterrey', id: 'America/Monterrey', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Montevideo', id: 'America/Montevideo', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Montserrat', id: 'America/Montserrat', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Nassau', id: 'America/Nassau', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/New_York', id: 'America/New_York', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Nipigon', id: 'America/Nipigon', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Nome', id: 'America/Nome', category: 'America' },
            { offset: '−02:00', text: '(GMT−02:00) America/Noronha', id: 'America/Noronha', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/North_Dakota/Beulah', id: 'America/North_Dakota/Beulah', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/North_Dakota/Center', id: 'America/North_Dakota/Center', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/North_Dakota/New_Salem', id: 'America/North_Dakota/New_Salem', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Nuuk', id: 'America/NuukAmerica/Nuuk', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Ojinaga', id: 'America/Ojinaga', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Panama', id: 'America/Panama', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Pangnirtung', id: 'America/Pangnirtung', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Paramaribo', id: 'America/Paramaribo', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Phoenix', id: 'America/Phoenix', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Port-au-Prince', id: 'America/Port-au-Prince', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Port_of_Spain', id: 'America/Port_of_Spain', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Porto_Velho', id: 'America/Porto_Velho', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Puerto_Rico', id: 'America/Puerto_Rico', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Punta_Arenas', id: 'America/Punta_Arenas', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Rainy_River', id: 'America/Rainy_River', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Rankin_Inlet', id: 'America/Rankin_Inlet', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Recife', id: 'America/Recife', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Regina', id: 'America/Regina', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Resolute', id: 'America/Resolute', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Rio_Branco', id: 'America/Rio_Branco', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Santarem', id: 'America/Santarem', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Santiago', id: 'America/Santiago', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Santo_Domingo', id: 'America/Santo_Domingo', category: 'America' },
            { offset: '−03:00', text: '(GMT−03:00) America/Sao_Paulo', id: 'America/Sao_Paulo', category: 'America' },
            { offset: '−01:00', text: '(GMT−01:00) America/Scoresbysund', id: 'America/Scoresbysund', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Sitka', id: 'America/Sitka', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/St_Barthelemy', id: 'America/St_Barthelemy', category: 'America' },
            { offset: '−03:30', text: '(GMT−03:30) America/St_Johns', id: 'America/St_Johns', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/St_Kitts', id: 'America/St_Kitts', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/St_Lucia', id: 'America/St_Lucia', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/St_Thomas', id: 'America/St_Thomas', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/St_Vincent', id: 'America/St_Vincent', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Swift_Current', id: 'America/Swift_Current', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Tegucigalpa', id: 'America/Tegucigalpa', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Thule', id: 'America/Thule', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Thunder_Bay', id: 'America/Thunder_Bay', category: 'America' },
            { offset: '−08:00', text: '(GMT−08:00) America/Tijuana', id: 'America/Tijuana', category: 'America' },
            { offset: '−05:00', text: '(GMT−05:00) America/Toronto', id: 'America/Toronto', category: 'America' },
            { offset: '−04:00', text: '(GMT−04:00) America/Tortola', id: 'America/Tortola', category: 'America' },
            { offset: '−08:00', text: '(GMT−08:00) America/Vancouver', id: 'America/Vancouver', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Whitehorse', id: 'America/Whitehorse', category: 'America' },
            { offset: '−06:00', text: '(GMT−06:00) America/Winnipeg', id: 'America/Winnipeg', category: 'America' },
            { offset: '−09:00', text: '(GMT−09:00) America/Yakutat', id: 'America/Yakutat', category: 'America' },
            { offset: '−07:00', text: '(GMT−07:00) America/Yellowknife', id: 'America/Yellowknife', category: 'America' },
        ]
  },
    {
        id: 2, text: 'Antarctica',
        children: [
            { offset: '+11:00', text: '(GMT+11:00) Antarctica/Casey', id: 'Antarctica/Casey', category: 'Antarctica' },
            { offset: '+07:00', text: '(GMT+07:00) Antarctica/Davis', id: 'Antarctica/Davis', category: 'Antarctica' },
            { offset: '+10:00', text: '(GMT+10:00) Antarctica/DumontDUrville', id: 'Antarctica/DumontDUrville', category: 'Antarctica' },
            { offset: '+10:00', text: '(GMT+10:00) Antarctica/Macquarie', id: 'Antarctica/Macquarie', category: 'Antarctica' },
            { offset: '+05:00', text: '(GMT+05:00) Antarctica/Mawson', id: 'Antarctica/Mawson', category: 'Antarctica' },
            { offset: '+12:00', text: '(GMT+12:00) Antarctica/McMurdo', id: 'Antarctica/McMurdo', category: 'Antarctica' },
            { offset: '−03:00', text: '(GMT−03:00) Antarctica/Palmer', id: 'Antarctica/Palmer', category: 'Antarctica' },
            { offset: '−03:00', text: '(GMT−03:00) Antarctica/Rothera', id: 'Antarctica/Rothera', category: 'Antarctica' },
            { offset: '+03:00', text: '(GMT+03:00) Antarctica/Syowa', id: 'Antarctica/Syowa', category: 'Antarctica' },
            { offset: '+00:00', text: '(GMT+00:00) Antarctica/Troll', id: 'Antarctica/Troll', category: 'Antarctica' },
            { offset: '+06:00', text: '(GMT+06:00) Antarctica/Vostok', id: 'Antarctica/Vostok', category: 'Antarctica' },
        ]
  },
    {
        id: 3, text: 'Arctic',
        children: [
            { offset: '+01:00', text: '(GMT+01:00) Arctic/Longyearbyen', id: 'Arctic/Longyearbyen', category: 'Arctic' },
        ]
  },
    {
        id: 4, text: 'Asia',
        children: [
            { offset: '+03:00', text: '(GMT+03:00) Asia/Aden', id: 'Asia/Aden', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Almaty', id: 'Asia/Almaty', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Amman', id: 'Asia/Amman', category: 'Asia' },
            { offset: '+12:00', text: '(GMT+12:00) Asia/Anadyr', id: 'Asia/Anadyr', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Aqtau', id: 'Asia/Aqtau', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Aqtobe', id: 'Asia/Aqtobe', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Ashgabat', id: 'Asia/Ashgabat', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Atyrau', id: 'Asia/Atyrau', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Baghdad', id: 'Asia/Baghdad', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Bahrain', id: 'Asia/Bahrain', category: 'Asia' },
            { offset: '+04:00', text: '(GMT+04:00) Asia/Baku', id: 'Asia/Baku', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Bangkok', id: 'Asia/Bangkok', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Barnaul', id: 'Asia/Barnaul', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Beirut', id: 'Asia/Beirut', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Bishkek', id: 'Asia/Bishkek', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Brunei', id: 'Asia/Brunei', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Chita', id: 'Asia/Chita', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Choibalsan', id: 'Asia/Choibalsan', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Colombo', id: 'Asia/Colombo', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Damascus', id: 'Asia/Damascus', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Dhaka', id: 'Asia/Dhaka', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Dili', id: 'Asia/Dili', category: 'Asia' },
            { offset: '+04:00', text: '(GMT+04:00) Asia/Dubai', id: 'Asia/Dubai', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Dushanbe', id: 'Asia/Dushanbe', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Famagusta', id: 'Asia/Famagusta', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Gaza', id: 'Asia/Gaza', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Hebron', id: 'Asia/Hebron', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Ho_Chi_Minh', id: 'Asia/Ho_Chi_Minh', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Hong_Kong', id: 'Asia/Hong_Kong', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Hovd', id: 'Asia/Hovd', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Irkutsk', id: 'Asia/Irkutsk', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Jakarta', id: 'Asia/Jakarta', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Jayapura', id: 'Asia/Jayapura', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Jerusalem', id: 'Asia/Jerusalem', category: 'Asia' },
            { offset: '+04:30', text: '(GMT+04:30) Asia/Kabul', id: 'Asia/Kabul', category: 'Asia' },
            { offset: '+12:00', text: '(GMT+12:00) Asia/Kamchatka', id: 'Asia/Kamchatka', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Karachi', id: 'Asia/Karachi', category: 'Asia' },
            { offset: '+05:45', text: '(GMT+05:45) Asia/Kathmandu', id: 'Asia/Kathmandu', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Khandyga', id: 'Asia/Khandyga', category: 'Asia' },
            { offset: '+05:30', text: '(GMT+05:30) Asia/Kolkata', id: 'Asia/Kolkata', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Krasnoyarsk', id: 'Asia/Krasnoyarsk', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Kuala_Lumpur', id: 'Asia/Kuala_Lumpur', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Kuching', id: 'Asia/Kuching', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Kuwait', id: 'Asia/Kuwait', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Macau', id: 'Asia/Macau', category: 'Asia' },
            { offset: '+11:00', text: '(GMT+11:00) Asia/Magadan', id: 'Asia/Magadan', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Makassar', id: 'Asia/Makassar', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Manila', id: 'Asia/Manila', category: 'Asia' },
            { offset: '+04:00', text: '(GMT+04:00) Asia/Muscat', id: 'Asia/Muscat', category: 'Asia' },
            { offset: '+02:00', text: '(GMT+02:00) Asia/Nicosia', id: 'Asia/Nicosia', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Novokuznetsk', id: 'Asia/Novokuznetsk', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Novosibirsk', id: 'Asia/Novosibirsk', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Omsk', id: 'Asia/Omsk', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Oral', id: 'Asia/Oral', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Phnom_Penh', id: 'Asia/Phnom_Penh', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Pontianak', id: 'Asia/Pontianak', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Pyongyang', id: 'Asia/Pyongyang', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Qatar', id: 'Asia/Qatar', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Qostanay', id: 'Asia/Qostanay', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Qyzylorda', id: 'Asia/Qyzylorda', category: 'Asia' },
            { offset: '+03:00', text: '(GMT+03:00) Asia/Riyadh', id: 'Asia/Riyadh', category: 'Asia' },
            { offset: '+11:00', text: '(GMT+11:00) Asia/Sakhalin', id: 'Asia/Sakhalin', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Samarkand', id: 'Asia/Samarkand', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Seoul', id: 'Asia/Seoul', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Shanghai', id: 'Asia/Shanghai', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Singapore', id: 'Asia/Singapore', category: 'Asia' },
            { offset: '+11:00', text: '(GMT+11:00) Asia/Srednekolymsk', id: 'Asia/Srednekolymsk', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Taipei', id: 'Asia/Taipei', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Tashkent', id: 'Asia/Tashkent', category: 'Asia' },
            { offset: '+04:00', text: '(GMT+04:00) Asia/Tbilisi', id: 'Asia/Tbilisi', category: 'Asia' },
            { offset: '+03:30', text: '(GMT+03:30) Asia/Tehran', id: 'Asia/Tehran', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Thimphu', id: 'Asia/Thimphu', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Tokyo', id: 'Asia/Tokyo', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Tomsk', id: 'Asia/Tomsk', category: 'Asia' },
            { offset: '+08:00', text: '(GMT+08:00) Asia/Ulaanbaatar', id: 'Asia/Ulaanbaatar', category: 'Asia' },
            { offset: '+06:00', text: '(GMT+06:00) Asia/Urumqi', id: 'Asia/Urumqi', category: 'Asia' },
            { offset: '+10:00', text: '(GMT+10:00) Asia/Ust-Nera', id: 'Asia/Ust-Nera', category: 'Asia' },
            { offset: '+07:00', text: '(GMT+07:00) Asia/Vientiane', id: 'Asia/Vientiane', category: 'Asia' },
            { offset: '+10:00', text: '(GMT+10:00) Asia/Vladivostok', id: 'Asia/Vladivostok', category: 'Asia' },
            { offset: '+09:00', text: '(GMT+09:00) Asia/Yakutsk', id: 'Asia/Yakutsk', category: 'Asia' },
            { offset: '+06:30', text: '(GMT+06:30) Asia/Yangon', id: 'Asia/Yangon', category: 'Asia' },
            { offset: '+05:00', text: '(GMT+05:00) Asia/Yekaterinburg', id: 'Asia/Yekaterinburg', category: 'Asia' },
            { offset: '+04:00', text: '(GMT+04:00) Asia/Yerevan', id: 'Asia/Yerevan', category: 'Asia' },
        ]
  },
    {
        id: 5, text: 'Atlantic',
        children: [
            { offset: '−01:00', text: '(GMT−01:00) Atlantic/Azores', id: 'Atlantic/Azores', category: 'Atlantic' },
            { offset: '−04:00', text: '(GMT−04:00) Atlantic/Bermuda', id: 'Atlantic/Bermuda', category: 'Atlantic' },
            { offset: '+00:00', text: '(GMT+00:00) Atlantic/Canary', id: 'Atlantic/Canary', category: 'Atlantic' },
            { offset: '−01:00', text: '(GMT−01:00) Atlantic/Cape_Verde', id: 'Atlantic/Cape_Verde', category: 'Atlantic' },
            { offset: '+00:00', text: '(GMT+00:00) Atlantic/Faroe', id: 'Atlantic/Faroe', category: 'Atlantic' },
            { offset: '+00:00', text: '(GMT+00:00) Atlantic/Madeira', id: 'Atlantic/Madeira', category: 'Atlantic' },
            { offset: '+00:00', text: '(GMT+00:00) Atlantic/Reykjavik', id: 'Atlantic/Reykjavik', category: 'Atlantic' },
            { offset: '−02:00', text: '(GMT−02:00) Atlantic/South_Georgia', id: 'Atlantic/South_Georgia', category: 'Atlantic' },
            { offset: '+00:00', text: '(GMT+00:00) Atlantic/St_Helena', id: 'Atlantic/St_Helena', category: 'Atlantic' },
            { offset: '−03:00', text: '(GMT−03:00) Atlantic/Stanley', id: 'Atlantic/Stanley', category: 'Atlantic' },
        ]
  },
    {
        id: 6, text: 'Australia',
        children: [
            { offset: '+09:30', text: '(GMT+09:30) Australia/Adelaide', id: 'Australia/Adelaide', category: 'Australia' },
            { offset: '+10:00', text: '(GMT+10:00) Australia/Brisbane', id: 'Australia/Brisbane', category: 'Australia' },
            { offset: '+09:30', text: '(GMT+09:30) Australia/Broken_Hill', id: 'Australia/Broken_Hill', category: 'Australia' },
            { offset: '+09:30', text: '(GMT+09:30) Australia/Darwin', id: 'Australia/Darwin', category: 'Australia' },
            { offset: '+08:45', text: '(GMT+08:45) Australia/Eucla', id: 'Australia/Eucla', category: 'Australia' },
            { offset: '+10:00', text: '(GMT+10:00) Australia/Hobart', id: 'Australia/Hobart', category: 'Australia' },
            { offset: '+10:00', text: '(GMT+10:00) Australia/Lindeman', id: 'Australia/Lindeman', category: 'Australia' },
            { offset: '+10:30', text: '(GMT+10:30) Australia/Lord_Howe', id: 'Australia/Lord_Howe', category: 'Australia' },
            { offset: '+10:00', text: '(GMT+10:00) Australia/Melbourne', id: 'Australia/Melbourne', category: 'Australia' },
            { offset: '+08:00', text: '(GMT+08:00) Australia/Perth', id: 'Australia/Perth', category: 'Australia' },
            { offset: '+10:00', text: '(GMT+10:00) Australia/Sydney', id: 'Australia/Sydney', category: 'Australia' },
        ]
  },
    {
        id: 7, text: 'Europe',
        children: [
            { offset: '+01:00', text: '(GMT+01:00) Europe/Amsterdam', id: 'Europe/Amsterdam', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Andorra', id: 'Europe/Andorra', category: 'Europe' },
            { offset: '+04:00', text: '(GMT+04:00) Europe/Astrakhan', id: 'Europe/Astrakhan', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Athens', id: 'Europe/Athens', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Belgrade', id: 'Europe/Belgrade', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Berlin', id: 'Europe/Berlin', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Bratislava', id: 'Europe/Bratislava', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Brussels', id: 'Europe/Brussels', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Bucharest', id: 'Europe/Bucharest', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Budapest', id: 'Europe/Budapest', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Busingen', id: 'Europe/Busingen', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Chisinau', id: 'Europe/Chisinau', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Copenhagen', id: 'Europe/Copenhagen', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Dublin', id: 'Europe/Dublin', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Gibraltar', id: 'Europe/Gibraltar', category: 'Europe' },
            { offset: '+00:00', text: '(GMT+00:00) Europe/Guernsey', id: 'Europe/Guernsey', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Helsinki', id: 'Europe/Helsinki', category: 'Europe' },
            { offset: '+00:00', text: '(GMT+00:00) Europe/Isle_of_Man', id: 'Europe/Isle_of_Man', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Istanbul', id: 'Europe/Istanbul', category: 'Europe' },
            { offset: '+00:00', text: '(GMT+00:00) Europe/Jersey', id: 'Europe/Jersey', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Kaliningrad', id: 'Europe/Kaliningrad', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Kiev', id: 'Europe/Kiev', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Kirov', id: 'Europe/Kirov', category: 'Europe' },
            { offset: '+00:00', text: '(GMT+00:00) Europe/Lisbon', id: 'Europe/Lisbon', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Ljubljana', id: 'Europe/Ljubljana', category: 'Europe' },
            { offset: '+00:00', text: '(GMT+00:00) Europe/London', id: 'Europe/London', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Luxembourg', id: 'Europe/Luxembourg', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Madrid', id: 'Europe/Madrid', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Malta', id: 'Europe/Malta', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Mariehamn', id: 'Europe/Mariehamn', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Minsk', id: 'Europe/Minsk', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Monaco', id: 'Europe/Monaco', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Moscow', id: 'Europe/Moscow', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Oslo', id: 'Europe/Oslo', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Paris', id: 'Europe/Paris', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Podgorica', id: 'Europe/Podgorica', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Prague', id: 'Europe/Prague', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Riga', id: 'Europe/Riga', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Rome', id: 'Europe/Rome', category: 'Europe' },
            { offset: '+04:00', text: '(GMT+04:00) Europe/Samara', id: 'Europe/Samara', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/San_Marino', id: 'Europe/San_Marino', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Sarajevo', id: 'Europe/Sarajevo', category: 'Europe' },
            { offset: '+04:00', text: '(GMT+04:00) Europe/Saratov', id: 'Europe/Saratov', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Simferopol', id: 'Europe/SimferopolEurope/Simferopol', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Skopje', id: 'Europe/Skopje', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Sofia', id: 'Europe/Sofia', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Stockholm', id: 'Europe/Stockholm', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Tallinn', id: 'Europe/Tallinn', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Tirane', id: 'Europe/Tirane', category: 'Europe' },
            { offset: '+04:00', text: '(GMT+04:00) Europe/Ulyanovsk', id: 'Europe/Ulyanovsk', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Uzhgorod', id: 'Europe/Uzhgorod', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Vaduz', id: 'Europe/Vaduz', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Vatican', id: 'Europe/Vatican', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Vienna', id: 'Europe/Vienna', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Vilnius', id: 'Europe/Vilnius', category: 'Europe' },
            { offset: '+03:00', text: '(GMT+03:00) Europe/Volgograd', id: 'Europe/Volgograd', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Warsaw', id: 'Europe/Warsaw', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Zagreb', id: 'Europe/Zagreb', category: 'Europe' },
            { offset: '+02:00', text: '(GMT+02:00) Europe/Zaporozhye', id: 'Europe/Zaporozhye', category: 'Europe' },
            { offset: '+01:00', text: '(GMT+01:00) Europe/Zurich', id: 'Europe/Zurich', category: 'Europe' },
        ]
  },
    {
        id: 8, text: 'Indian',
        children: [
            { offset: '+03:00', text: '(GMT+03:00) Indian/Antananarivo', id: 'Indian/Antananarivo', category: 'Indian' },
            { offset: '+06:00', text: '(GMT+06:00) Indian/Chagos', id: 'Indian/Chagos', category: 'Indian' },
            { offset: '+07:00', text: '(GMT+07:00) Indian/Christmas', id: 'Indian/Christmas', category: 'Indian' },
            { offset: '+06:30', text: '(GMT+06:30) Indian/Cocos', id: 'Indian/Cocos', category: 'Indian' },
            { offset: '+03:00', text: '(GMT+03:00) Indian/Comoro', id: 'Indian/Comoro', category: 'Indian' },
            { offset: '+05:00', text: '(GMT+05:00) Indian/Kerguelen', id: 'Indian/Kerguelen', category: 'Indian' },
            { offset: '+04:00', text: '(GMT+04:00) Indian/Mahe', id: 'Indian/Mahe', category: 'Indian' },
            { offset: '+05:00', text: '(GMT+05:00) Indian/Maldives', id: 'Indian/Maldives', category: 'Indian' },
            { offset: '+04:00', text: '(GMT+04:00) Indian/Mauritius', id: 'Indian/Mauritius', category: 'Indian' },
            { offset: '+03:00', text: '(GMT+03:00) Indian/Mayotte', id: 'Indian/Mayotte', category: 'Indian' },
            { offset: '+04:00', text: '(GMT+04:00) Indian/Reunion', id: 'Indian/Reunion', category: 'Indian' },
        ]
  },
    {
        id: 9, text: 'Pacific',
        children: [
            { offset: '+13:00', text: '(GMT+13:00) Pacific/Apia', id: 'Pacific/Apia', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Auckland', id: 'Pacific/Auckland', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Bougainville', id: 'Pacific/Bougainville', category: 'Pacific' },
            { offset: '+12:45', text: '(GMT+12:45) Pacific/Chatham', id: 'Pacific/Chatham', category: 'Pacific' },
            { offset: '+10:00', text: '(GMT+10:00) Pacific/Chuuk', id: 'Pacific/Chuuk', category: 'Pacific' },
            { offset: '−06:00', text: '(GMT−06:00) Pacific/Easter', id: 'Pacific/Easter', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Efate', id: 'Pacific/Efate', category: 'Pacific' },
            { offset: '+13:00', text: '(GMT+13:00) Pacific/Enderbury', id: 'Pacific/Enderbury', category: 'Pacific' },
            { offset: '+13:00', text: '(GMT+13:00) Pacific/Fakaofo', id: 'Pacific/Fakaofo', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Fiji', id: 'Pacific/Fiji', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Funafuti', id: 'Pacific/Funafuti', category: 'Pacific' },
            { offset: '−06:00', text: '(GMT−06:00) Pacific/Galapagos', id: 'Pacific/Galapagos', category: 'Pacific' },
            { offset: '−09:00', text: '(GMT−09:00) Pacific/Gambier', id: 'Pacific/Gambier', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Guadalcanal', id: 'Pacific/Guadalcanal', category: 'Pacific' },
            { offset: '+10:00', text: '(GMT+10:00) Pacific/Guam', id: 'Pacific/Guam', category: 'Pacific' },
            { offset: '−10:00', text: '(GMT−10:00) Pacific/Honolulu', id: 'Pacific/Honolulu', category: 'Pacific' },
            { offset: '+14:00', text: '(GMT+14:00) Pacific/Kiritimati', id: 'Pacific/Kiritimati', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Kosrae', id: 'Pacific/Kosrae', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Kwajalein', id: 'Pacific/Kwajalein', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Majuro', id: 'Pacific/Majuro', category: 'Pacific' },
            { offset: '−09:30', text: '(GMT−09:30) Pacific/Marquesas', id: 'Pacific/Marquesas', category: 'Pacific' },
            { offset: '−11:00', text: '(GMT−11:00) Pacific/Midway', id: 'Pacific/Midway', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Nauru', id: 'Pacific/Nauru', category: 'Pacific' },
            { offset: '−11:00', text: '(GMT−11:00) Pacific/Niue', id: 'Pacific/Niue', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Norfolk', id: 'Pacific/Norfolk', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Noumea', id: 'Pacific/Noumea', category: 'Pacific' },
            { offset: '−11:00', text: '(GMT−11:00) Pacific/Pago_Pago', id: 'Pacific/Pago_Pago', category: 'Pacific' },
            { offset: '+09:00', text: '(GMT+09:00) Pacific/Palau', id: 'Pacific/Palau', category: 'Pacific' },
            { offset: '−08:00', text: '(GMT−08:00) Pacific/Pitcairn', id: 'Pacific/Pitcairn', category: 'Pacific' },
            { offset: '+11:00', text: '(GMT+11:00) Pacific/Pohnpei', id: 'Pacific/Pohnpei', category: 'Pacific' },
            { offset: '+10:00', text: '(GMT+10:00) Pacific/Port_Moresby', id: 'Pacific/Port_Moresby', category: 'Pacific' },
            { offset: '−10:00', text: '(GMT−10:00) Pacific/Rarotonga', id: 'Pacific/Rarotonga', category: 'Pacific' },
            { offset: '+10:00', text: '(GMT+10:00) Pacific/Saipan', id: 'Pacific/Saipan', category: 'Pacific' },
            { offset: '−10:00', text: '(GMT−10:00) Pacific/Tahiti', id: 'Pacific/Tahiti', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Tarawa', id: 'Pacific/Tarawa', category: 'Pacific' },
            { offset: '+13:00', text: '(GMT+13:00) Pacific/Tongatapu', id: 'Pacific/Tongatapu', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Wake', id: 'Pacific/Wake', category: 'Pacific' },
            { offset: '+12:00', text: '(GMT+12:00) Pacific/Wallis', id: 'Pacific/Wallis', category: 'Pacific' },
        ]
  },

];

/**
 *
 * @type {Array.<{ offset: string, text: string, id: string }>}
 */
module.exports.minimalTimezoneSet = [
    { offset: '-11:00', text: '(GMT-11:00) Pago Pago', id: 'Pacific/Pago_Pago' },
    { offset: '-10:00', text: '(GMT-10:00) Hawaii Time', id: 'Pacific/Honolulu' },
    { offset: '-10:00', text: '(GMT-10:00) Tahiti', id: 'Pacific/Tahiti' },
    { offset: '-09:00', text: '(GMT-09:00) Alaska Time', id: 'America/Anchorage' },
    { offset: '-08:00', text: '(GMT-08:00) Pacific Time', id: 'America/Los_Angeles' },
    { offset: '-07:00', text: '(GMT-07:00) Mountain Time', id: 'America/Denver' },
    { offset: '-06:00', text: '(GMT-06:00) Central Time', id: 'America/Chicago' },
    { offset: '-05:00', text: '(GMT-05:00) Eastern Time', id: 'America/New_York' },
    { offset: '-04:00', text: '(GMT-04:00) Atlantic Time - Halifax', id: 'America/Halifax' },
    { offset: '-03:00', text: '(GMT-03:00) Buenos Aires', id: 'America/Argentina/Buenos_Aires' },
    { offset: '-02:00', text: '(GMT-02:00) Sao Paulo', id: 'America/Sao_Paulo' },
    { offset: '-01:00', text: '(GMT-01:00) Azores', id: 'Atlantic/Azores' },
    { offset: '+00:00', text: '(GMT+00:00) London', id: 'Europe/London' },
    { offset: '+01:00', text: '(GMT+01:00) Berlin', id: 'Europe/Berlin' },
    { offset: '+02:00', text: '(GMT+02:00) Helsinki', id: 'Europe/Helsinki' },
    { offset: '+03:00', text: '(GMT+03:00) Istanbul', id: 'Europe/Istanbul' },
    { offset: '+04:00', text: '(GMT+04:00) Dubai', id: 'Asia/Dubai' },
    { offset: '+04:30', text: '(GMT+04:30) Kabul', id: 'Asia/Kabul' },
    { offset: '+05:00', text: '(GMT+05:00) Maldives', id: 'Indian/Maldives' },
    { offset: '+05:30', text: '(GMT+05:30) India Standard Time', id: 'Asia/Calcutta' },
    { offset: '+05:45', text: '(GMT+05:45) Kathmandu', id: 'Asia/Kathmandu' },
    { offset: '+06:00', text: '(GMT+06:00) Dhaka', id: 'Asia/Dhaka' },
    { offset: '+06:30', text: '(GMT+06:30) Cocos', id: 'Indian/Cocos' },
    { offset: '+07:00', text: '(GMT+07:00) Bangkok', id: 'Asia/Bangkok' },
    { offset: '+08:00', text: '(GMT+08:00) Hong Kong', id: 'Asia/Hong_Kong' },
    { offset: '+08:30', text: '(GMT+08:30) Pyongyang', id: 'Asia/Pyongyang' },
    { offset: '+09:00', text: '(GMT+09:00) Tokyo', id: 'Asia/Tokyo' },
    { offset: '+09:30', text: '(GMT+09:30) Central Time - Darwin', id: 'Australia/Darwin' },
    { offset: '+10:00', text: '(GMT+10:00) Eastern Time - Brisbane', id: 'Australia/Brisbane' },
    { offset: '+10:30', text: '(GMT+10:30) Central Time - Adelaide', id: 'Australia/Adelaide' },
    { offset: '+11:00', text: '(GMT+11:00) Eastern Time - Melbourne, Sydney', id: 'Australia/Sydney' },
    { offset: '+12:00', text: '(GMT+12:00) Nauru', id: 'Pacific/Nauru' },
    { offset: '+13:00', text: '(GMT+13:00) Auckland', id: 'Pacific/Auckland' },
    { offset: '+14:00', text: '(GMT+14:00) Kiritimati', id: 'Pacific/Kiritimati' }
];
