/**
 * @fileoverview
 *
 * This package contains an array of timezones based on conventional options found online.
 * It does not follow any complete data set, but all names are according to the tz format:
 * https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
 *
 * More specifically, the fields in the array are:
 * – offset, a string from '-11:00' to '+14:00' representing the UTC offset
 * - label, a readable label that contains the offset and a longer, descriptive name of the timezone
 * - tzCode, the value from the tz standard
 *
 * Install:
 *  `npm install compact-timezone-list --save`
 *   # or
 *  `yarn add compact-timezone-list`
 *
 *
 *  Example:
 *  const { defaultTimezoneSet } = require('compact-timezone-list');
 *  // or
 *  const { minimalTimezoneSet } = require('compact-timezone-list');
 *
 *  Details:
 *  - The 'defaultTimezoneSet' export provides a long list of options, with multiple
 *  – The `minimalTimezoneSet` export provides one option per offset type, with
 *  a favourite chosen to represent each offset. This is mostly targeted to small,
 *  western-focused apps. But, every UTC offset is included.
 */

/**
 *
 * @type {Array.<{ offset: string, label: string, tzCode: string }>}
 */
module.exports.defaultTimezoneSet = [
    {
        id: 0, text: 'Africa',
        children: [
            { offset: '+00:00', text: '(GMT+00:00) Africa/Abidjan', id: 'Africa/Abidjan', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Abidjan', tzCode: 'Africa/Abidjan', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Accra', tzCode: 'Africa/Accra', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Addis_Ababa', tzCode: 'Africa/Addis_Ababa', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Algiers', tzCode: 'Africa/Algiers', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Asmara', tzCode: 'Africa/Asmara', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Bamako', tzCode: 'Africa/Bamako', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Bangui', tzCode: 'Africa/Bangui', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Banjul', tzCode: 'Africa/Banjul', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Bissau', tzCode: 'Africa/Bissau', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Blantyre', tzCode: 'Africa/Blantyre', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Brazzaville', tzCode: 'Africa/Brazzaville', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Bujumbura', tzCode: 'Africa/Bujumbura', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Cairo', tzCode: 'Africa/Cairo', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Casablanca', tzCode: 'Africa/Casablanca', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Ceuta', tzCode: 'Africa/Ceuta', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Conakry', tzCode: 'Africa/Conakry', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Dakar', tzCode: 'Africa/Dakar', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Dar_es_Salaam', tzCode: 'Africa/Dar_es_Salaam', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Djibouti', tzCode: 'Africa/Djibouti', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Douala', tzCode: 'Africa/Douala', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/El_Aaiun', tzCode: 'Africa/El_Aaiun', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Freetown', tzCode: 'Africa/Freetown', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Gaborone', tzCode: 'Africa/Gaborone', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Harare', tzCode: '	Africa/Harare', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Johannesburg', tzCode: 'Africa/Johannesburg', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Juba', tzCode: 'Africa/Juba', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Kampala', tzCode: 'Africa/Kampala', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Khartoum', tzCode: 'Africa/Khartoum', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Kigali', tzCode: 'Africa/Kigali', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Kinshasa', tzCode: 'Africa/Kinshasa', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Lagos', tzCode: 'Africa/Lagos', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Libreville', tzCode: 'Africa/Libreville', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Lome', tzCode: 'Africa/Lome', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Luanda', tzCode: 'Africa/Luanda', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Lubumbashi', tzCode: 'Africa/Lubumbashi', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Lusaka', tzCode: 'Africa/Lusaka', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Malabo	', tzCode: 'Africa/Malabo	', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Maputo', tzCode: 'Africa/Maputo', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Maseru', tzCode: 'Africa/Maseru', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Mbabane', tzCode: 'Africa/Mbabane', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Mogadishu', tzCode: 'Africa/Mogadishu', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Monrovia', tzCode: 'Africa/Monrovia', category: 'Africa' },
            { offset: '+03:00', label: '(GMT+03:00) Africa/Nairobi', tzCode: 'Africa/Nairobi', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Ndjamena', tzCode: 'Africa/Ndjamena', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Niamey', tzCode: 'Africa/Niamey', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Nouakchott', tzCode: 'Africa/Nouakchott', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Ouagadougou', tzCode: 'Africa/Ouagadougou', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Porto-Novo', tzCode: 'Africa/Porto-Novo', category: 'Africa' },
            { offset: '+00:00', label: '(GMT+00:00) Africa/Sao_Tome', tzCode: 'Africa/Sao_Tome', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Tripoli', tzCode: 'Africa/Tripoli', category: 'Africa' },
            { offset: '+01:00', label: '(GMT+01:00) Africa/Tunis', tzCode: 'Africa/Tunis', category: 'Africa' },
            { offset: '+02:00', label: '(GMT+02:00) Africa/Windhoek', tzCode: 'Africa/Windhoek', category: 'Africa' },
        ]
  },
    {
        id: 1, text: 'America',
        children: [
            { offset: '−10:00', label: '(GMT−10:00) America/Adak', tzCode: 'America/Adak', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Anchorage', tzCode: 'America/Anchorage', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Anguilla', tzCode: 'America/Anguilla', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Antigua', tzCode: 'America/Antigua', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Araguaina', tzCode: 'America/Araguaina', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Buenos_Aires', tzCode: 'America/Argentina/Buenos_Aires', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Catamarca', tzCode: 'America/Argentina/Catamarca', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Cordoba', tzCode: 'America/Argentina/Cordoba', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Jujuy', tzCode: 'America/Argentina/Jujuy', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/La_Rioja', tzCode: 'America/Argentina/La_Rioja', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Mendoza', tzCode: 'America/Argentina/Mendoza', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Rio_Gallegos', tzCode: 'America/Argentina/Rio_Gallegos', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Salta', tzCode: 'America/Argentina/Salta', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/San_Juan', tzCode: 'America/Argentina/San_Juan', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/San_Luis', tzCode: 'America/Argentina/San_Luis', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Tucuman', tzCode: 'America/Argentina/Tucuman', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Argentina/Ushuaia', tzCode: 'America/Argentina/Ushuaia', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Aruba', tzCode: 'America/Aruba', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Asuncion', tzCode: 'America/Asuncion', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Atikokan', tzCode: 'America/Atikokan', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Bahia', tzCode: 'America/Bahia', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Bahia_Banderas', tzCode: 'America/Bahia_Banderas', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Barbados', tzCode: 'America/Barbados', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Belem', tzCode: 'America/Belem', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Belize', tzCode: 'America/Belize', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Blanc-Sablon', tzCode: 'America/Blanc-Sablon', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Boa_Vista', tzCode: 'America/Boa_Vista', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Bogota', tzCode: 'America/Bogota', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Boise', tzCode: 'America/Boise', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Cambridge_Bay', tzCode: 'America/Cambridge_Bay', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Campo_Grande', tzCode: 'America/Campo_Grande', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Cancun', tzCode: 'America/Cancun', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Caracas', tzCode: 'America/Caracas', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Cayenne', tzCode: 'America/Cayenne', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Cayman', tzCode: 'America/Cayman', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Chicago', tzCode: 'America/Chicago', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Chihuahua', tzCode: 'America/Chihuahua', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Costa_Rica', tzCode: 'America/Costa_Rica', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Creston', tzCode: 'America/Creston', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Cuiaba', tzCode: 'America/Cuiaba', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Curacao', tzCode: 'America/Curacao', category: 'America' },
            { offset: '+00:00', label: '(GMT+00:00) America/Danmarkshavn', tzCode: 'America/Danmarkshavn', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Dawson', tzCode: 'America/Dawson', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Dawson_Creek', tzCode: 'America/Dawson_Creek', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Denver', tzCode: 'America/Denver', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Detroit', tzCode: 'America/Detroit', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Dominica', tzCode: 'America/Dominica', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Edmonton', tzCode: 'America/Edmonton', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Eirunepe', tzCode: 'America/Eirunepe', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/El_Salvador', tzCode: 'America/El_Salvador', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Fort_Nelson', tzCode: 'America/Fort_Nelson', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Fortaleza', tzCode: 'America/Fortaleza', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Glace_Bay', tzCode: 'America/Glace_Bay', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Goose_Bay', tzCode: 'America/Goose_Bay', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Grand_Turk', tzCode: 'America/Grand_Turk', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Grenada', tzCode: 'America/Grenada', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Guadeloupe', tzCode: 'America/Guadeloupe', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Guatemala', tzCode: 'America/Guatemala', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Guayaquil', tzCode: 'America/Guayaquil', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Guyana', tzCode: 'America/Guyana', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Halifax', tzCode: 'America/Halifax', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Havana', tzCode: 'America/Havana', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Hermosillo', tzCode: 'America/Hermosillo', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Indianapolis', tzCode: 'America/Indiana/Indianapolis', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Indiana/Knox', tzCode: 'America/Indiana/Knox', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Marengo', tzCode: 'America/Indiana/Marengo', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Petersburg', tzCode: 'America/Indiana/Petersburg', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Indiana/Tell_City', tzCode: 'America/Indiana/Tell_City', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Vevay', tzCode: 'America/Indiana/Vevay', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Vincennes', tzCode: 'America/Indiana/Vincennes', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Indiana/Winamac', tzCode: 'America/Indiana/Winamac', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Inuvik', tzCode: 'America/Inuvik', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Iqaluit', tzCode: 'America/Iqaluit', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Jamaica', tzCode: 'America/Jamaica', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Juneau', tzCode: 'America/Juneau', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Kentucky/Louisville', tzCode: 'America/Kentucky/Louisville', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Kentucky/Monticello', tzCode: 'America/Kentucky/Monticello', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Kralendijk', tzCode: 'America/Kralendijk', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/La_Paz', tzCode: 'America/La_Paz', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Lima', tzCode: 'America/Lima', category: 'America' },
            { offset: '−08:00', label: '(GMT−08:00) America/Los_Angeles', tzCode: 'America/Los_Angeles', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Lower_Princes', tzCode: 'America/Lower_Princes', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Maceio', tzCode: 'America/Maceio', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Managua', tzCode: 'America/Managua', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Manaus', tzCode: 'America/Manaus', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Marigot', tzCode: 'America/Marigot', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Martinique', tzCode: 'America/Martinique', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Matamoros', tzCode: 'America/Matamoros', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Mazatlan', tzCode: 'America/Mazatlan', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Menominee', tzCode: 'America/Menominee', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Merida', tzCode: 'America/Merida', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Metlakatla', tzCode: 'America/Metlakatla', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Mexico_City', tzCode: 'America/Mexico_City', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Miquelon', tzCode: 'America/Miquelon', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Moncton', tzCode: 'America/Moncton', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Monterrey', tzCode: 'America/Monterrey', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Montevideo', tzCode: 'America/Montevideo', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Montserrat', tzCode: 'America/Montserrat', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Nassau', tzCode: 'America/Nassau', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/New_York', tzCode: 'America/New_York', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Nipigon', tzCode: 'America/Nipigon', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Nome', tzCode: 'America/Nome', category: 'America' },
            { offset: '−02:00', label: '(GMT−02:00) America/Noronha', tzCode: 'America/Noronha', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/North_Dakota/Beulah', tzCode: 'America/North_Dakota/Beulah', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/North_Dakota/Center', tzCode: 'America/North_Dakota/Center', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/North_Dakota/New_Salem', tzCode: 'America/North_Dakota/New_Salem', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Nuuk', tzCode: 'America/NuukAmerica/Nuuk', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Ojinaga', tzCode: 'America/Ojinaga', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Panama', tzCode: 'America/Panama', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Pangnirtung', tzCode: 'America/Pangnirtung', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Paramaribo', tzCode: 'America/Paramaribo', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Phoenix', tzCode: 'America/Phoenix', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Port-au-Prince', tzCode: 'America/Port-au-Prince', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Port_of_Spain', tzCode: 'America/Port_of_Spain', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Porto_Velho', tzCode: 'America/Porto_Velho', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Puerto_Rico', tzCode: 'America/Puerto_Rico', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Punta_Arenas', tzCode: 'America/Punta_Arenas', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Rainy_River', tzCode: 'America/Rainy_River', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Rankin_Inlet', tzCode: 'America/Rankin_Inlet', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Recife', tzCode: 'America/Recife', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Regina', tzCode: 'America/Regina', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Resolute', tzCode: 'America/Resolute', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Rio_Branco', tzCode: 'America/Rio_Branco', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Santarem', tzCode: 'America/Santarem', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Santiago', tzCode: 'America/Santiago', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Santo_Domingo', tzCode: 'America/Santo_Domingo', category: 'America' },
            { offset: '−03:00', label: '(GMT−03:00) America/Sao_Paulo', tzCode: 'America/Sao_Paulo', category: 'America' },
            { offset: '−01:00', label: '(GMT−01:00) America/Scoresbysund', tzCode: 'America/Scoresbysund', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Sitka', tzCode: 'America/Sitka', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/St_Barthelemy', tzCode: 'America/St_Barthelemy', category: 'America' },
            { offset: '−03:30', label: '(GMT−03:30) America/St_Johns', tzCode: 'America/St_Johns', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/St_Kitts', tzCode: 'America/St_Kitts', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/St_Lucia', tzCode: 'America/St_Lucia', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/St_Thomas', tzCode: 'America/St_Thomas', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/St_Vincent', tzCode: 'America/St_Vincent', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Swift_Current', tzCode: 'America/Swift_Current', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Tegucigalpa', tzCode: 'America/Tegucigalpa', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Thule', tzCode: 'America/Thule', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Thunder_Bay', tzCode: 'America/Thunder_Bay', category: 'America' },
            { offset: '−08:00', label: '(GMT−08:00) America/Tijuana', tzCode: 'America/Tijuana', category: 'America' },
            { offset: '−05:00', label: '(GMT−05:00) America/Toronto', tzCode: 'America/Toronto', category: 'America' },
            { offset: '−04:00', label: '(GMT−04:00) America/Tortola', tzCode: 'America/Tortola', category: 'America' },
            { offset: '−08:00', label: '(GMT−08:00) America/Vancouver', tzCode: 'America/Vancouver', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Whitehorse', tzCode: 'America/Whitehorse', category: 'America' },
            { offset: '−06:00', label: '(GMT−06:00) America/Winnipeg', tzCode: 'America/Winnipeg', category: 'America' },
            { offset: '−09:00', label: '(GMT−09:00) America/Yakutat', tzCode: 'America/Yakutat', category: 'America' },
            { offset: '−07:00', label: '(GMT−07:00) America/Yellowknife', tzCode: 'America/Yellowknife', category: 'America' },
        ]
  },
    {
        id: 2, text: 'Antarctica',
        children: [
            { offset: '+11:00', label: '(GMT+11:00) Antarctica/Casey', tzCode: 'Antarctica/Casey', category: 'Antarctica' },
            { offset: '+07:00', label: '(GMT+07:00) Antarctica/Davis', tzCode: 'Antarctica/Davis', category: 'Antarctica' },
            { offset: '+10:00', label: '(GMT+10:00) Antarctica/DumontDUrville', tzCode: 'Antarctica/DumontDUrville', category: 'Antarctica' },
            { offset: '+10:00', label: '(GMT+10:00) Antarctica/Macquarie', tzCode: 'Antarctica/Macquarie', category: 'Antarctica' },
            { offset: '+05:00', label: '(GMT+05:00) Antarctica/Mawson', tzCode: 'Antarctica/Mawson', category: 'Antarctica' },
            { offset: '+12:00', label: '(GMT+12:00) Antarctica/McMurdo', tzCode: 'Antarctica/McMurdo', category: 'Antarctica' },
            { offset: '−03:00', label: '(GMT−03:00) Antarctica/Palmer', tzCode: 'Antarctica/Palmer', category: 'Antarctica' },
            { offset: '−03:00', label: '(GMT−03:00) Antarctica/Rothera', tzCode: 'Antarctica/Rothera', category: 'Antarctica' },
            { offset: '+03:00', label: '(GMT+03:00) Antarctica/Syowa', tzCode: 'Antarctica/Syowa', category: 'Antarctica' },
            { offset: '+00:00', label: '(GMT+00:00) Antarctica/Troll', tzCode: 'Antarctica/Troll', category: 'Antarctica' },
            { offset: '+06:00', label: '(GMT+06:00) Antarctica/Vostok', tzCode: 'Antarctica/Vostok', category: 'Antarctica' },
        ]
  },
    {
        id: 3, text: 'Arctic',
        children: [
            { offset: '+01:00', label: '(GMT+01:00) Arctic/Longyearbyen', tzCode: 'Arctic/Longyearbyen', category: 'Arctic' },
        ]
  },
    {
        id: 4, text: 'Asia',
        children: [
            { offset: '+03:00', label: '(GMT+03:00) Asia/Aden', tzCode: 'Asia/Aden', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Almaty', tzCode: 'Asia/Almaty', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Amman', tzCode: 'Asia/Amman', category: 'Asia' },
            { offset: '+12:00', label: '(GMT+12:00) Asia/Anadyr', tzCode: 'Asia/Anadyr', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Aqtau', tzCode: 'Asia/Aqtau', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Aqtobe', tzCode: 'Asia/Aqtobe', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Ashgabat', tzCode: 'Asia/Ashgabat', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Atyrau', tzCode: 'Asia/Atyrau', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Baghdad', tzCode: 'Asia/Baghdad', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Bahrain', tzCode: 'Asia/Bahrain', category: 'Asia' },
            { offset: '+04:00', label: '(GMT+04:00) Asia/Baku', tzCode: 'Asia/Baku', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Bangkok', tzCode: 'Asia/Bangkok', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Barnaul', tzCode: 'Asia/Barnaul', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Beirut', tzCode: 'Asia/Beirut', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Bishkek', tzCode: 'Asia/Bishkek', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Brunei', tzCode: 'Asia/Brunei', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Chita', tzCode: 'Asia/Chita', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Choibalsan', tzCode: 'Asia/Choibalsan', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Colombo', tzCode: 'Asia/Colombo', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Damascus', tzCode: 'Asia/Damascus', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Dhaka', tzCode: 'Asia/Dhaka', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Dili', tzCode: 'Asia/Dili', category: 'Asia' },
            { offset: '+04:00', label: '(GMT+04:00) Asia/Dubai', tzCode: 'Asia/Dubai', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Dushanbe', tzCode: 'Asia/Dushanbe', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Famagusta', tzCode: 'Asia/Famagusta', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Gaza', tzCode: 'Asia/Gaza', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Hebron', tzCode: 'Asia/Hebron', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Ho_Chi_Minh', tzCode: 'Asia/Ho_Chi_Minh', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Hong_Kong', tzCode: 'Asia/Hong_Kong', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Hovd', tzCode: 'Asia/Hovd', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Irkutsk', tzCode: 'Asia/Irkutsk', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Jakarta', tzCode: 'Asia/Jakarta', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Jayapura', tzCode: 'Asia/Jayapura', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Jerusalem', tzCode: 'Asia/Jerusalem', category: 'Asia' },
            { offset: '+04:30', label: '(GMT+04:30) Asia/Kabul', tzCode: 'Asia/Kabul', category: 'Asia' },
            { offset: '+12:00', label: '(GMT+12:00) Asia/Kamchatka', tzCode: 'Asia/Kamchatka', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Karachi', tzCode: 'Asia/Karachi', category: 'Asia' },
            { offset: '+05:45', label: '(GMT+05:45) Asia/Kathmandu', tzCode: 'Asia/Kathmandu', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Khandyga', tzCode: 'Asia/Khandyga', category: 'Asia' },
            { offset: '+05:30', label: '(GMT+05:30) Asia/Kolkata', tzCode: 'Asia/Kolkata', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Krasnoyarsk', tzCode: 'Asia/Krasnoyarsk', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Kuala_Lumpur', tzCode: 'Asia/Kuala_Lumpur', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Kuching', tzCode: 'Asia/Kuching', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Kuwait', tzCode: 'Asia/Kuwait', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Macau', tzCode: 'Asia/Macau', category: 'Asia' },
            { offset: '+11:00', label: '(GMT+11:00) Asia/Magadan', tzCode: 'Asia/Magadan', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Makassar', tzCode: 'Asia/Makassar', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Manila', tzCode: 'Asia/Manila', category: 'Asia' },
            { offset: '+04:00', label: '(GMT+04:00) Asia/Muscat', tzCode: 'Asia/Muscat', category: 'Asia' },
            { offset: '+02:00', label: '(GMT+02:00) Asia/Nicosia', tzCode: 'Asia/Nicosia', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Novokuznetsk', tzCode: 'Asia/Novokuznetsk', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Novosibirsk', tzCode: 'Asia/Novosibirsk', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Omsk', tzCode: 'Asia/Omsk', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Oral', tzCode: 'Asia/Oral', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Phnom_Penh', tzCode: 'Asia/Phnom_Penh', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Pontianak', tzCode: 'Asia/Pontianak', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Pyongyang', tzCode: 'Asia/Pyongyang', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Qatar', tzCode: 'Asia/Qatar', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Qostanay', tzCode: 'Asia/Qostanay', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Qyzylorda', tzCode: 'Asia/Qyzylorda', category: 'Asia' },
            { offset: '+03:00', label: '(GMT+03:00) Asia/Riyadh', tzCode: 'Asia/Riyadh', category: 'Asia' },
            { offset: '+11:00', label: '(GMT+11:00) Asia/Sakhalin', tzCode: 'Asia/Sakhalin', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Samarkand', tzCode: 'Asia/Samarkand', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Seoul', tzCode: 'Asia/Seoul', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Shanghai', tzCode: 'Asia/Shanghai', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Singapore', tzCode: 'Asia/Singapore', category: 'Asia' },
            { offset: '+11:00', label: '(GMT+11:00) Asia/Srednekolymsk', tzCode: 'Asia/Srednekolymsk', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Taipei', tzCode: 'Asia/Taipei', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Tashkent', tzCode: 'Asia/Tashkent', category: 'Asia' },
            { offset: '+04:00', label: '(GMT+04:00) Asia/Tbilisi', tzCode: 'Asia/Tbilisi', category: 'Asia' },
            { offset: '+03:30', label: '(GMT+03:30) Asia/Tehran', tzCode: 'Asia/Tehran', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Thimphu', tzCode: 'Asia/Thimphu', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Tokyo', tzCode: 'Asia/Tokyo', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Tomsk', tzCode: 'Asia/Tomsk', category: 'Asia' },
            { offset: '+08:00', label: '(GMT+08:00) Asia/Ulaanbaatar', tzCode: 'Asia/Ulaanbaatar', category: 'Asia' },
            { offset: '+06:00', label: '(GMT+06:00) Asia/Urumqi', tzCode: 'Asia/Urumqi', category: 'Asia' },
            { offset: '+10:00', label: '(GMT+10:00) Asia/Ust-Nera', tzCode: 'Asia/Ust-Nera', category: 'Asia' },
            { offset: '+07:00', label: '(GMT+07:00) Asia/Vientiane', tzCode: 'Asia/Vientiane', category: 'Asia' },
            { offset: '+10:00', label: '(GMT+10:00) Asia/Vladivostok', tzCode: 'Asia/Vladivostok', category: 'Asia' },
            { offset: '+09:00', label: '(GMT+09:00) Asia/Yakutsk', tzCode: 'Asia/Yakutsk', category: 'Asia' },
            { offset: '+06:30', label: '(GMT+06:30) Asia/Yangon', tzCode: 'Asia/Yangon', category: 'Asia' },
            { offset: '+05:00', label: '(GMT+05:00) Asia/Yekaterinburg', tzCode: 'Asia/Yekaterinburg', category: 'Asia' },
            { offset: '+04:00', label: '(GMT+04:00) Asia/Yerevan', tzCode: 'Asia/Yerevan', category: 'Asia' },
        ]
  },
    {
        id: 5, text: 'Atlantic',
        children: [
            { offset: '−01:00', label: '(GMT−01:00) Atlantic/Azores', tzCode: 'Atlantic/Azores', category: 'Atlantic' },
            { offset: '−04:00', label: '(GMT−04:00) Atlantic/Bermuda', tzCode: 'Atlantic/Bermuda', category: 'Atlantic' },
            { offset: '+00:00', label: '(GMT+00:00) Atlantic/Canary', tzCode: 'Atlantic/Canary', category: 'Atlantic' },
            { offset: '−01:00', label: '(GMT−01:00) Atlantic/Cape_Verde', tzCode: 'Atlantic/Cape_Verde', category: 'Atlantic' },
            { offset: '+00:00', label: '(GMT+00:00) Atlantic/Faroe', tzCode: 'Atlantic/Faroe', category: 'Atlantic' },
            { offset: '+00:00', label: '(GMT+00:00) Atlantic/Madeira', tzCode: 'Atlantic/Madeira', category: 'Atlantic' },
            { offset: '+00:00', label: '(GMT+00:00) Atlantic/Reykjavik', tzCode: 'Atlantic/Reykjavik', category: 'Atlantic' },
            { offset: '−02:00', label: '(GMT−02:00) Atlantic/South_Georgia', tzCode: 'Atlantic/South_Georgia', category: 'Atlantic' },
            { offset: '+00:00', label: '(GMT+00:00) Atlantic/St_Helena', tzCode: 'Atlantic/St_Helena', category: 'Atlantic' },
            { offset: '−03:00', label: '(GMT−03:00) Atlantic/Stanley', tzCode: 'Atlantic/Stanley', category: 'Atlantic' },
        ]
  },
    {
        id: 6, text: 'Australia',
        children: [
            { offset: '+09:30', label: '(GMT+09:30) Australia/Adelaide', tzCode: 'Australia/Adelaide', category: 'Australia' },
            { offset: '+10:00', label: '(GMT+10:00) Australia/Brisbane', tzCode: 'Australia/Brisbane', category: 'Australia' },
            { offset: '+09:30', label: '(GMT+09:30) Australia/Broken_Hill', tzCode: 'Australia/Broken_Hill', category: 'Australia' },
            { offset: '+09:30', label: '(GMT+09:30) Australia/Darwin', tzCode: 'Australia/Darwin', category: 'Australia' },
            { offset: '+08:45', label: '(GMT+08:45) Australia/Eucla', tzCode: 'Australia/Eucla', category: 'Australia' },
            { offset: '+10:00', label: '(GMT+10:00) Australia/Hobart', tzCode: 'Australia/Hobart', category: 'Australia' },
            { offset: '+10:00', label: '(GMT+10:00) Australia/Lindeman', tzCode: 'Australia/Lindeman', category: 'Australia' },
            { offset: '+10:30', label: '(GMT+10:30) Australia/Lord_Howe', tzCode: 'Australia/Lord_Howe', category: 'Australia' },
            { offset: '+10:00', label: '(GMT+10:00) Australia/Melbourne', tzCode: 'Australia/Melbourne', category: 'Australia' },
            { offset: '+08:00', label: '(GMT+08:00) Australia/Perth', tzCode: 'Australia/Perth', category: 'Australia' },
            { offset: '+10:00', label: '(GMT+10:00) Australia/Sydney', tzCode: 'Australia/Sydney', category: 'Australia' },
        ]
  },
    {
        id: 7, text: 'Europe',
        children: [
            { offset: '+01:00', label: '(GMT+01:00) Europe/Amsterdam', tzCode: 'Europe/Amsterdam', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Andorra', tzCode: 'Europe/Andorra', category: 'Europe' },
            { offset: '+04:00', label: '(GMT+04:00) Europe/Astrakhan', tzCode: 'Europe/Astrakhan', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Athens', tzCode: 'Europe/Athens', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Belgrade', tzCode: 'Europe/Belgrade', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Berlin', tzCode: 'Europe/Berlin', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Bratislava', tzCode: 'Europe/Bratislava', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Brussels', tzCode: 'Europe/Brussels', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Bucharest', tzCode: 'Europe/Bucharest', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Budapest', tzCode: 'Europe/Budapest', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Busingen', tzCode: 'Europe/Busingen', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Chisinau', tzCode: 'Europe/Chisinau', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Copenhagen', tzCode: 'Europe/Copenhagen', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Dublin', tzCode: 'Europe/Dublin', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Gibraltar', tzCode: 'Europe/Gibraltar', category: 'Europe' },
            { offset: '+00:00', label: '(GMT+00:00) Europe/Guernsey', tzCode: 'Europe/Guernsey', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Helsinki', tzCode: 'Europe/Helsinki', category: 'Europe' },
            { offset: '+00:00', label: '(GMT+00:00) Europe/Isle_of_Man', tzCode: 'Europe/Isle_of_Man', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Istanbul', tzCode: 'Europe/Istanbul', category: 'Europe' },
            { offset: '+00:00', label: '(GMT+00:00) Europe/Jersey', tzCode: 'Europe/Jersey', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Kaliningrad', tzCode: 'Europe/Kaliningrad', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Kiev', tzCode: 'Europe/Kiev', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Kirov', tzCode: 'Europe/Kirov', category: 'Europe' },
            { offset: '+00:00', label: '(GMT+00:00) Europe/Lisbon', tzCode: 'Europe/Lisbon', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Ljubljana', tzCode: 'Europe/Ljubljana', category: 'Europe' },
            { offset: '+00:00', label: '(GMT+00:00) Europe/London', tzCode: 'Europe/London', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Luxembourg', tzCode: 'Europe/Luxembourg', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Madrid', tzCode: 'Europe/Madrid', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Malta', tzCode: 'Europe/Malta', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Mariehamn', tzCode: 'Europe/Mariehamn', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Minsk', tzCode: 'Europe/Minsk', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Monaco', tzCode: 'Europe/Monaco', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Moscow', tzCode: 'Europe/Moscow', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Oslo', tzCode: 'Europe/Oslo', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Paris', tzCode: 'Europe/Paris', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Podgorica', tzCode: 'Europe/Podgorica', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Prague', tzCode: 'Europe/Prague', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Riga', tzCode: 'Europe/Riga', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Rome', tzCode: 'Europe/Rome', category: 'Europe' },
            { offset: '+04:00', label: '(GMT+04:00) Europe/Samara', tzCode: 'Europe/Samara', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/San_Marino', tzCode: 'Europe/San_Marino', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Sarajevo', tzCode: 'Europe/Sarajevo', category: 'Europe' },
            { offset: '+04:00', label: '(GMT+04:00) Europe/Saratov', tzCode: 'Europe/Saratov', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Simferopol', tzCode: 'Europe/SimferopolEurope/Simferopol', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Skopje', tzCode: 'Europe/Skopje', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Sofia', tzCode: 'Europe/Sofia', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Stockholm', tzCode: 'Europe/Stockholm', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Tallinn', tzCode: 'Europe/Tallinn', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Tirane', tzCode: 'Europe/Tirane', category: 'Europe' },
            { offset: '+04:00', label: '(GMT+04:00) Europe/Ulyanovsk', tzCode: 'Europe/Ulyanovsk', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Uzhgorod', tzCode: 'Europe/Uzhgorod', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Vaduz', tzCode: 'Europe/Vaduz', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Vatican', tzCode: 'Europe/Vatican', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Vienna', tzCode: 'Europe/Vienna', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Vilnius', tzCode: 'Europe/Vilnius', category: 'Europe' },
            { offset: '+03:00', label: '(GMT+03:00) Europe/Volgograd', tzCode: 'Europe/Volgograd', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Warsaw', tzCode: 'Europe/Warsaw', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Zagreb', tzCode: 'Europe/Zagreb', category: 'Europe' },
            { offset: '+02:00', label: '(GMT+02:00) Europe/Zaporozhye', tzCode: 'Europe/Zaporozhye', category: 'Europe' },
            { offset: '+01:00', label: '(GMT+01:00) Europe/Zurich', tzCode: 'Europe/Zurich', category: 'Europe' },
        ]
  },
    {
        id: 8, text: 'Indian',
        children: [
            { offset: '+03:00', label: '(GMT+03:00) Indian/Antananarivo', tzCode: 'Indian/Antananarivo', category: 'Indian' },
            { offset: '+06:00', label: '(GMT+06:00) Indian/Chagos', tzCode: 'Indian/Chagos', category: 'Indian' },
            { offset: '+07:00', label: '(GMT+07:00) Indian/Christmas', tzCode: 'Indian/Christmas', category: 'Indian' },
            { offset: '+06:30', label: '(GMT+06:30) Indian/Cocos', tzCode: 'Indian/Cocos', category: 'Indian' },
            { offset: '+03:00', label: '(GMT+03:00) Indian/Comoro', tzCode: 'Indian/Comoro', category: 'Indian' },
            { offset: '+05:00', label: '(GMT+05:00) Indian/Kerguelen', tzCode: 'Indian/Kerguelen', category: 'Indian' },
            { offset: '+04:00', label: '(GMT+04:00) Indian/Mahe', tzCode: 'Indian/Mahe', category: 'Indian' },
            { offset: '+05:00', label: '(GMT+05:00) Indian/Maldives', tzCode: 'Indian/Maldives', category: 'Indian' },
            { offset: '+04:00', label: '(GMT+04:00) Indian/Mauritius', tzCode: 'Indian/Mauritius', category: 'Indian' },
            { offset: '+03:00', label: '(GMT+03:00) Indian/Mayotte', tzCode: 'Indian/Mayotte', category: 'Indian' },
            { offset: '+04:00', label: '(GMT+04:00) Indian/Reunion', tzCode: 'Indian/Reunion', category: 'Indian' },
        ]
  },
    {
        id: 9, text: 'Pacific',
        children: [
            { offset: '+13:00', label: '(GMT+13:00) Pacific/Apia', tzCode: 'Pacific/Apia', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Auckland', tzCode: 'Pacific/Auckland', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Bougainville', tzCode: 'Pacific/Bougainville', category: 'Pacific' },
            { offset: '+12:45', label: '(GMT+12:45) Pacific/Chatham', tzCode: 'Pacific/Chatham', category: 'Pacific' },
            { offset: '+10:00', label: '(GMT+10:00) Pacific/Chuuk', tzCode: 'Pacific/Chuuk', category: 'Pacific' },
            { offset: '−06:00', label: '(GMT−06:00) Pacific/Easter', tzCode: 'Pacific/Easter', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Efate', tzCode: 'Pacific/Efate', category: 'Pacific' },
            { offset: '+13:00', label: '(GMT+13:00) Pacific/Enderbury', tzCode: 'Pacific/Enderbury', category: 'Pacific' },
            { offset: '+13:00', label: '(GMT+13:00) Pacific/Fakaofo', tzCode: 'Pacific/Fakaofo', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Fiji', tzCode: 'Pacific/Fiji', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Funafuti', tzCode: 'Pacific/Funafuti', category: 'Pacific' },
            { offset: '−06:00', label: '(GMT−06:00) Pacific/Galapagos', tzCode: 'Pacific/Galapagos', category: 'Pacific' },
            { offset: '−09:00', label: '(GMT−09:00) Pacific/Gambier', tzCode: 'Pacific/Gambier', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Guadalcanal', tzCode: 'Pacific/Guadalcanal', category: 'Pacific' },
            { offset: '+10:00', label: '(GMT+10:00) Pacific/Guam', tzCode: 'Pacific/Guam', category: 'Pacific' },
            { offset: '−10:00', label: '(GMT−10:00) Pacific/Honolulu', tzCode: 'Pacific/Honolulu', category: 'Pacific' },
            { offset: '+14:00', label: '(GMT+14:00) Pacific/Kiritimati', tzCode: 'Pacific/Kiritimati', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Kosrae', tzCode: 'Pacific/Kosrae', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Kwajalein', tzCode: 'Pacific/Kwajalein', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Majuro', tzCode: 'Pacific/Majuro', category: 'Pacific' },
            { offset: '−09:30', label: '(GMT−09:30) Pacific/Marquesas', tzCode: 'Pacific/Marquesas', category: 'Pacific' },
            { offset: '−11:00', label: '(GMT−11:00) Pacific/Midway', tzCode: 'Pacific/Midway', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Nauru', tzCode: 'Pacific/Nauru', category: 'Pacific' },
            { offset: '−11:00', label: '(GMT−11:00) Pacific/Niue', tzCode: 'Pacific/Niue', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Norfolk', tzCode: 'Pacific/Norfolk', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Noumea', tzCode: 'Pacific/Noumea', category: 'Pacific' },
            { offset: '−11:00', label: '(GMT−11:00) Pacific/Pago_Pago', tzCode: 'Pacific/Pago_Pago', category: 'Pacific' },
            { offset: '+09:00', label: '(GMT+09:00) Pacific/Palau', tzCode: 'Pacific/Palau', category: 'Pacific' },
            { offset: '−08:00', label: '(GMT−08:00) Pacific/Pitcairn', tzCode: 'Pacific/Pitcairn', category: 'Pacific' },
            { offset: '+11:00', label: '(GMT+11:00) Pacific/Pohnpei', tzCode: 'Pacific/Pohnpei', category: 'Pacific' },
            { offset: '+10:00', label: '(GMT+10:00) Pacific/Port_Moresby', tzCode: 'Pacific/Port_Moresby', category: 'Pacific' },
            { offset: '−10:00', label: '(GMT−10:00) Pacific/Rarotonga', tzCode: 'Pacific/Rarotonga', category: 'Pacific' },
            { offset: '+10:00', label: '(GMT+10:00) Pacific/Saipan', tzCode: 'Pacific/Saipan', category: 'Pacific' },
            { offset: '−10:00', label: '(GMT−10:00) Pacific/Tahiti', tzCode: 'Pacific/Tahiti', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Tarawa', tzCode: 'Pacific/Tarawa', category: 'Pacific' },
            { offset: '+13:00', label: '(GMT+13:00) Pacific/Tongatapu', tzCode: 'Pacific/Tongatapu', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Wake', tzCode: 'Pacific/Wake', category: 'Pacific' },
            { offset: '+12:00', label: '(GMT+12:00) Pacific/Wallis', tzCode: 'Pacific/Wallis', category: 'Pacific' },
        ]
  },

];

/**
 *
 * @type {Array.<{ offset: string, label: string, tzCode: string }>}
 */
module.exports.minimalTimezoneSet = [
    { offset: '-11:00', label: '(GMT-11:00) Pago Pago', tzCode: 'Pacific/Pago_Pago' },
    { offset: '-10:00', label: '(GMT-10:00) Hawaii Time', tzCode: 'Pacific/Honolulu' },
    { offset: '-10:00', label: '(GMT-10:00) Tahiti', tzCode: 'Pacific/Tahiti' },
    { offset: '-09:00', label: '(GMT-09:00) Alaska Time', tzCode: 'America/Anchorage' },
    { offset: '-08:00', label: '(GMT-08:00) Pacific Time', tzCode: 'America/Los_Angeles' },
    { offset: '-07:00', label: '(GMT-07:00) Mountain Time', tzCode: 'America/Denver' },
    { offset: '-06:00', label: '(GMT-06:00) Central Time', tzCode: 'America/Chicago' },
    { offset: '-05:00', label: '(GMT-05:00) Eastern Time', tzCode: 'America/New_York' },
    { offset: '-04:00', label: '(GMT-04:00) Atlantic Time - Halifax', tzCode: 'America/Halifax' },
    { offset: '-03:00', label: '(GMT-03:00) Buenos Aires', tzCode: 'America/Argentina/Buenos_Aires' },
    { offset: '-02:00', label: '(GMT-02:00) Sao Paulo', tzCode: 'America/Sao_Paulo' },
    { offset: '-01:00', label: '(GMT-01:00) Azores', tzCode: 'Atlantic/Azores' },
    { offset: '+00:00', label: '(GMT+00:00) London', tzCode: 'Europe/London' },
    { offset: '+01:00', label: '(GMT+01:00) Berlin', tzCode: 'Europe/Berlin' },
    { offset: '+02:00', label: '(GMT+02:00) Helsinki', tzCode: 'Europe/Helsinki' },
    { offset: '+03:00', label: '(GMT+03:00) Istanbul', tzCode: 'Europe/Istanbul' },
    { offset: '+04:00', label: '(GMT+04:00) Dubai', tzCode: 'Asia/Dubai' },
    { offset: '+04:30', label: '(GMT+04:30) Kabul', tzCode: 'Asia/Kabul' },
    { offset: '+05:00', label: '(GMT+05:00) Maldives', tzCode: 'Indian/Maldives' },
    { offset: '+05:30', label: '(GMT+05:30) India Standard Time', tzCode: 'Asia/Calcutta' },
    { offset: '+05:45', label: '(GMT+05:45) Kathmandu', tzCode: 'Asia/Kathmandu' },
    { offset: '+06:00', label: '(GMT+06:00) Dhaka', tzCode: 'Asia/Dhaka' },
    { offset: '+06:30', label: '(GMT+06:30) Cocos', tzCode: 'Indian/Cocos' },
    { offset: '+07:00', label: '(GMT+07:00) Bangkok', tzCode: 'Asia/Bangkok' },
    { offset: '+08:00', label: '(GMT+08:00) Hong Kong', tzCode: 'Asia/Hong_Kong' },
    { offset: '+08:30', label: '(GMT+08:30) Pyongyang', tzCode: 'Asia/Pyongyang' },
    { offset: '+09:00', label: '(GMT+09:00) Tokyo', tzCode: 'Asia/Tokyo' },
    { offset: '+09:30', label: '(GMT+09:30) Central Time - Darwin', tzCode: 'Australia/Darwin' },
    { offset: '+10:00', label: '(GMT+10:00) Eastern Time - Brisbane', tzCode: 'Australia/Brisbane' },
    { offset: '+10:30', label: '(GMT+10:30) Central Time - Adelaide', tzCode: 'Australia/Adelaide' },
    { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Melbourne, Sydney', tzCode: 'Australia/Sydney' },
    { offset: '+12:00', label: '(GMT+12:00) Nauru', tzCode: 'Pacific/Nauru' },
    { offset: '+13:00', label: '(GMT+13:00) Auckland', tzCode: 'Pacific/Auckland' },
    { offset: '+14:00', label: '(GMT+14:00) Kiritimati', tzCode: 'Pacific/Kiritimati' }
];
